"""
White Label Reports - Create Branded SEO Reports
Generate professional, customized reports for your clients
"""

import streamlit as st
from datetime import datetime, timedelta
import random
import plotly.graph_objects as go
import plotly.express as px

# Page config
st.set_page_config(page_title="White Label Reports", page_icon="📄", layout="wide")

# Custom CSS
st.markdown("""
<style>
    .main-header {
        font-size: 2.5rem;
        font-weight: 700;
        color: #1a1a1a;
        margin-bottom: 0.5rem;
    }
    .sub-header {
        font-size: 1.1rem;
        color: #666;
        margin-bottom: 2rem;
    }
    .report-preview {
        background: white;
        padding: 2rem;
        border-radius: 12px;
        border: 2px solid #e0e0e0;
        box-shadow: 0 4px 12px rgba(0,0,0,0.1);
    }
    .template-card {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        color: white;
        padding: 1.5rem;
        border-radius: 12px;
        cursor: pointer;
        transition: transform 0.2s;
    }
    .template-card:hover {
        transform: translateY(-4px);
    }
</style>
""", unsafe_allow_html=True)

# Initialize session state
if 'report_config' not in st.session_state:
    st.session_state.report_config = {
        'logo': None,
        'company_name': 'Your Agency',
        'primary_color': '#667eea',
        'secondary_color': '#764ba2',
        'font': 'Arial',
        'footer_text': 'Generated by Your Agency'
    }

if 'saved_reports' not in st.session_state:
    st.session_state.saved_reports = []

# Header
st.markdown('<div class="main-header">📄 White Label Reports</div>', unsafe_allow_html=True)
st.markdown('<div class="sub-header">Create professional, branded SEO reports for your clients</div>', unsafe_allow_html=True)

# Summary metrics
col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric("Reports Generated", len(st.session_state.saved_reports))
with col2:
    st.metric("Templates", 5)
with col3:
    st.metric("This Month", random.randint(10, 30))
with col4:
    st.metric("Avg Generation Time", "2.3s")

st.markdown("---")

# Tabs
tab1, tab2, tab3, tab4 = st.tabs(["🎨 Create Report", "📋 Templates", "📊 Preview", "⚙️ Branding"])

with tab1:
    st.markdown("### 🎨 Create New Report")
    
    col1, col2 = st.columns([2, 1])
    
    with col1:
        # Report Configuration
        st.markdown("#### 📝 Report Details")
        
        report_name = st.text_input("Report Name", placeholder="Monthly SEO Report - January 2026")
        client_name = st.text_input("Client Name", placeholder="Acme Corporation")
        report_period = st.selectbox(
            "Report Period",
            options=['Last 7 days', 'Last 30 days', 'Last 90 days', 'Custom Range']
        )
        
        if report_period == 'Custom Range':
            col_a, col_b = st.columns(2)
            with col_a:
                start_date = st.date_input("Start Date")
            with col_b:
                end_date = st.date_input("End Date")
        
        st.markdown("#### 📊 Sections to Include")
        
        col_a, col_b = st.columns(2)
        
        with col_a:
            include_overview = st.checkbox("Executive Overview", value=True)
            include_keywords = st.checkbox("Keyword Rankings", value=True)
            include_traffic = st.checkbox("Traffic Analysis", value=True)
            include_backlinks = st.checkbox("Backlink Profile", value=False)
        
        with col_b:
            include_competitors = st.checkbox("Competitor Analysis", value=True)
            include_technical = st.checkbox("Technical SEO", value=False)
            include_content = st.checkbox("Content Performance", value=True)
            include_recommendations = st.checkbox("Recommendations", value=True)
        
        st.markdown("#### 🎯 Additional Options")
        
        report_format = st.radio(
            "Output Format",
            options=['PDF', 'PowerPoint', 'HTML', 'Google Slides'],
            horizontal=True
        )
        
        include_raw_data = st.checkbox("Include raw data tables")
        auto_send = st.checkbox("Auto-send to client email")
        
        if auto_send:
            recipient_email = st.text_input("Recipient Email", placeholder="client@example.com")
    
    with col2:
        st.markdown("#### 🎨 Branding Preview")
        
        st.markdown(f"""
        <div style="background: {st.session_state.report_config['primary_color']}; 
                    color: white; 
                    padding: 2rem; 
                    border-radius: 12px;
                    text-align: center;">
            <h2 style="margin: 0; font-family: {st.session_state.report_config['font']};">
                {st.session_state.report_config['company_name']}
            </h2>
            <p style="margin-top: 1rem; opacity: 0.9;">
                {report_name if report_name else 'Your Report Title'}
            </p>
        </div>
        """, unsafe_allow_html=True)
        
        st.markdown("---")
        
        st.markdown("#### 📋 Quick Templates")
        
        templates = [
            "Executive Summary",
            "Detailed Analysis",
            "Quick Overview",
            "Custom Template"
        ]
        
        for template in templates:
            if st.button(template, use_container_width=True):
                st.info(f"✅ Applied {template} template")
    
    st.markdown("---")
    
    if st.button("🚀 Generate Report", type="primary", use_container_width=True):
        with st.spinner("Generating your report..."):
            import time
            time.sleep(2)
            
            # Save report
            new_report = {
                'name': report_name or "Untitled Report",
                'client': client_name or "Unknown Client",
                'period': report_period,
                'format': report_format,
                'created': datetime.now(),
                'sections': [
                    'Overview' if include_overview else None,
                    'Keywords' if include_keywords else None,
                    'Traffic' if include_traffic else None,
                    'Backlinks' if include_backlinks else None,
                    'Competitors' if include_competitors else None,
                    'Technical' if include_technical else None,
                    'Content' if include_content else None,
                    'Recommendations' if include_recommendations else None
                ]
            }
            new_report['sections'] = [s for s in new_report['sections'] if s]
            
            st.session_state.saved_reports.append(new_report)
            
            st.success("✅ Report generated successfully!")
            st.balloons()
            
            # Download button
            st.download_button(
                label=f"📥 Download {report_format}",
                data=f"Sample {report_format} content for {report_name}",
                file_name=f"{report_name.replace(' ', '_')}.{report_format.lower()}",
                mime="application/pdf",
                use_container_width=True
            )

with tab2:
    st.markdown("### 📋 Report Templates")
    
    templates_data = [
        {
            'name': 'Executive Summary',
            'description': 'High-level overview for executives and decision makers',
            'sections': ['Overview', 'Key Metrics', 'ROI Analysis', 'Next Steps'],
            'pages': 5,
            'best_for': 'C-level executives'
        },
        {
            'name': 'Detailed Analysis',
            'description': 'Comprehensive report with in-depth data and analysis',
            'sections': ['Overview', 'Keywords', 'Traffic', 'Backlinks', 'Technical', 'Competitors'],
            'pages': 25,
            'best_for': 'Marketing teams'
        },
        {
            'name': 'Quick Overview',
            'description': 'Brief snapshot of key performance indicators',
            'sections': ['Key Metrics', 'Top Changes', 'Quick Wins'],
            'pages': 3,
            'best_for': 'Monthly check-ins'
        },
        {
            'name': 'Technical SEO Audit',
            'description': 'Focus on technical issues and opportunities',
            'sections': ['Site Health', 'Page Speed', 'Mobile Usability', 'Structured Data'],
            'pages': 15,
            'best_for': 'Development teams'
        },
        {
            'name': 'Competitor Benchmark',
            'description': 'Compare performance against top competitors',
            'sections': ['Market Position', 'Keyword Overlap', 'Content Gap Analysis'],
            'pages': 12,
            'best_for': 'Strategic planning'
        }
    ]
    
    for template in templates_data:
        with st.expander(f"**{template['name']}** - {template['description']}", expanded=False):
            col1, col2 = st.columns([2, 1])
            
            with col1:
                st.markdown(f"**Best for:** {template['best_for']}")
                st.markdown(f"**Pages:** ~{template['pages']} pages")
                st.markdown("**Sections included:**")
                for section in template['sections']:
                    st.markdown(f"• {section}")
            
            with col2:
                if st.button("Use Template", key=f"use_{template['name']}", use_container_width=True):
                    st.success(f"✅ {template['name']} template selected")
                
                if st.button("Preview", key=f"preview_{template['name']}", use_container_width=True):
                    st.info("Opening preview...")
                
                if st.button("Customize", key=f"custom_{template['name']}", use_container_width=True):
                    st.info("Opening customization...")
    
    st.markdown("---")
    
    col1, col2 = st.columns(2)
    
    with col1:
        if st.button("➕ Create Custom Template", use_container_width=True):
            st.info("Custom template builder coming soon!")
    
    with col2:
        if st.button("📥 Import Template", use_container_width=True):
            uploaded = st.file_uploader("Upload template file", type=['json'])

with tab3:
    st.markdown("### 📊 Report Preview")
    
    if not st.session_state.saved_reports:
        st.info("No reports generated yet. Create your first report in the 'Create Report' tab!")
    else:
        # Select report to preview
        report_to_preview = st.selectbox(
            "Select report to preview",
            options=[r['name'] for r in st.session_state.saved_reports]
        )
        
        report = next(r for r in st.session_state.saved_reports if r['name'] == report_to_preview)
        
        # Preview container
        st.markdown(f"""
        <div class="report-preview">
            <div style="text-align: center; margin-bottom: 2rem;">
                <h1 style="color: {st.session_state.report_config['primary_color']}; 
                           font-family: {st.session_state.report_config['font']};">
                    {st.session_state.report_config['company_name']}
                </h1>
                <h2 style="color: #333; margin-top: 1rem;">
                    {report['name']}
                </h2>
                <p style="color: #666; margin-top: 0.5rem;">
                    Prepared for {report['client']} | {report['created'].strftime('%B %d, %Y')}
                </p>
            </div>
        </div>
        """, unsafe_allow_html=True)
        
        st.markdown("---")
        
        # Sample sections based on what's included
        if 'Overview' in report['sections']:
            st.markdown("### 📊 Executive Overview")
            
            col1, col2, col3, col4 = st.columns(4)
            
            with col1:
                st.metric("Organic Traffic", "45,234", "+12.5%")
            with col2:
                st.metric("Keywords Ranking", "234", "+18")
            with col3:
                st.metric("Avg Position", "8.3", "-2.1")
            with col4:
                st.metric("Backlinks", "1,456", "+45")
        
        if 'Keywords' in report['sections']:
            st.markdown("### 🔑 Top Performing Keywords")
            
            keywords_data = {
                'Keyword': ['seo tools', 'keyword research', 'backlink checker', 'site audit', 'rank tracker'],
                'Position': [3, 5, 8, 12, 15],
                'Change': ['+2', '+3', '-1', '+5', '0'],
                'Traffic': [2340, 1890, 1234, 890, 567]
            }
            
            st.dataframe(keywords_data, use_container_width=True, hide_index=True)
        
        if 'Traffic' in report['sections']:
            st.markdown("### 📈 Traffic Trend")
            
            dates = [(datetime.now() - timedelta(days=x)).strftime("%Y-%m-%d") for x in range(30, 0, -1)]
            traffic = [random.randint(1000, 2000) for _ in range(30)]
            
            fig = go.Figure()
            fig.add_trace(go.Scatter(
                x=dates,
                y=traffic,
                mode='lines',
                name='Organic Traffic',
                fill='tozeroy',
                line=dict(color=st.session_state.report_config['primary_color'], width=3)
            ))
            
            fig.update_layout(
                xaxis_title="Date",
                yaxis_title="Sessions",
                height=300,
                showlegend=False
            )
            
            st.plotly_chart(fig, use_container_width=True)
        
        if 'Competitors' in report['sections']:
            st.markdown("### 🎯 Competitor Comparison")
            
            competitors_data = {
                'Competitor': ['competitor1.com', 'competitor2.com', 'competitor3.com', 'Your Site'],
                'Visibility': [75, 68, 62, 58],
                'Keywords': [450, 380, 320, 234],
                'Traffic': [125000, 98000, 87000, 45234]
            }
            
            fig = go.Figure(data=[
                go.Bar(name='Keywords', x=competitors_data['Competitor'], y=competitors_data['Keywords']),
                go.Bar(name='Traffic', x=competitors_data['Competitor'], 
                      y=[t/1000 for t in competitors_data['Traffic']])
            ])
            
            fig.update_layout(barmode='group', height=300)
            st.plotly_chart(fig, use_container_width=True)
        
        if 'Recommendations' in report['sections']:
            st.markdown("### 💡 Recommendations")
            
            recommendations = [
                "🎯 Target 15 new high-volume keywords identified in content gap analysis",
                "🔧 Fix 8 technical issues affecting page speed and mobile usability",
                "📝 Create content for 'topic clusters' with high search potential",
                "🔗 Build relationships with 10 high-authority domains for backlinks",
                "📱 Optimize 12 pages for mobile-first indexing"
            ]
            
            for rec in recommendations:
                st.markdown(f"• {rec}")
        
        st.markdown("---")
        
        # Footer in preview
        st.markdown(f"""
        <div style="text-align: center; padding: 2rem; color: #666; border-top: 2px solid #e0e0e0;">
            {st.session_state.report_config['footer_text']}
        </div>
        """, unsafe_allow_html=True)
        
        # Action buttons
        col1, col2, col3 = st.columns(3)
        
        with col1:
            if st.button("📥 Download PDF", use_container_width=True):
                st.download_button(
                    label="Download",
                    data=f"PDF content for {report['name']}",
                    file_name=f"{report['name'].replace(' ', '_')}.pdf",
                    mime="application/pdf"
                )
        
        with col2:
            if st.button("📧 Email Report", use_container_width=True):
                st.success("✅ Report sent successfully!")
        
        with col3:
            if st.button("🔄 Regenerate", use_container_width=True):
                st.info("Regenerating report...")

with tab4:
    st.markdown("### ⚙️ Branding Settings")
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.markdown("#### 🎨 Visual Identity")
        
        company_name = st.text_input(
            "Company Name",
            value=st.session_state.report_config['company_name']
        )
        
        primary_color = st.color_picker(
            "Primary Color",
            value=st.session_state.report_config['primary_color']
        )
        
        secondary_color = st.color_picker(
            "Secondary Color",
            value=st.session_state.report_config['secondary_color']
        )
        
        font = st.selectbox(
            "Font Family",
            options=['Arial', 'Helvetica', 'Georgia', 'Times New Roman', 'Verdana', 'Courier'],
            index=0
        )
        
        logo_file = st.file_uploader("Upload Logo", type=['png', 'jpg', 'svg'])
        
        if logo_file:
            st.image(logo_file, width=200)
    
    with col2:
        st.markdown("#### 📝 Report Content")
        
        footer_text = st.text_area(
            "Footer Text",
            value=st.session_state.report_config['footer_text'],
            height=100
        )
        
        st.markdown("#### 📧 Email Settings")
        
        email_subject = st.text_input(
            "Default Email Subject",
            value="Your Monthly SEO Report"
        )
        
        email_message = st.text_area(
            "Default Email Message",
            value="Please find attached your monthly SEO performance report.",
            height=100
        )
    
    if st.button("💾 Save Branding Settings", type="primary", use_container_width=True):
        st.session_state.report_config.update({
            'company_name': company_name,
            'primary_color': primary_color,
            'secondary_color': secondary_color,
            'font': font,
            'footer_text': footer_text
        })
        st.success("✅ Branding settings saved!")
    
    st.markdown("---")
    
    # Preview of branding
    st.markdown("#### 👀 Preview")
    
    st.markdown(f"""
    <div style="background: {primary_color}; 
                color: white; 
                padding: 3rem; 
                border-radius: 12px;
                text-align: center;">
        <h1 style="margin: 0; font-family: {font};">
            {company_name}
        </h1>
        <p style="margin-top: 1rem; font-size: 1.2rem; opacity: 0.9;">
            Monthly SEO Performance Report
        </p>
        <div style="margin-top: 2rem; padding-top: 2rem; border-top: 1px solid rgba(255,255,255,0.3);">
            <p style="margin: 0; opacity: 0.8; font-size: 0.9rem;">
                {footer_text}
            </p>
        </div>
    </div>
    """, unsafe_allow_html=True)

# Footer
st.markdown("---")
st.markdown("💡 **Tip:** Customize your reports with your agency branding to provide a professional, white-labeled experience!")